"""MetaCache format exporter for taxonomic classification."""

from typing import Optional, Dict, Any, List
from pathlib import Path
import csv

from .base import DirectoryBasedExporter
from ..core.models import TaxonomyTree
from ..core.exceptions import ExportError
from ..utils.logging_config import get_logger

logger = get_logger(__name__)


class MetaCacheExporter(DirectoryBasedExporter):
    """Exporter for MetaCache taxonomy format.

    MetaCache supports multiple taxonomy file formats:
    1. NCBI taxonomy format (names.dmp, nodes.dmp) - default
    2. Assembly summary format with taxid column
    3. NCBI accession2taxid mapping files
    4. Taxid-annotated FASTA headers (for reference)

    The format is controlled by the 'format_type' parameter.
    """

    @property
    def exporter_name(self) -> str:
        return "metacache"

    @property
    def file_extensions(self) -> list[str]:
        return [".dmp", ".txt", ".tsv", ".fa", ".fna"]

    def export(self, tree: TaxonomyTree, output_path: Path, **kwargs: Any) -> None:
        """Export taxonomy tree in MetaCache format.

        Creates different files based on format_type:
        - 'ncbi_taxonomy': names.dmp, nodes.dmp (default)
        - 'assembly_summary': assembly_summary.txt with taxid column
        - 'accession2taxid': accession2taxid mapping file

        Args:
            tree: Taxonomy tree to export
            output_path: Output directory path
            **kwargs: Additional options
                - format_type: Export format ('ncbi_taxonomy', 'assembly_summary', 'accession2taxid')
                - compress: Compress output files (default: False)
                - include_genomes: Include genome mappings (default: True)
        """
        self._validate_tree(tree)
        self._ensure_output_path(output_path)

        logger.info(
            f"Exporting {tree.node_count} nodes to MetaCache format: {output_path}"
        )

        # Configuration options
        format_type = kwargs.get("format_type", "ncbi_taxonomy")
        compress = kwargs.get("compress", False)
        include_genomes = kwargs.get("include_genomes", True)

        if format_type == "ncbi_taxonomy":
            self._create_ncbi_taxonomy(tree, output_path, compress)
        elif format_type == "assembly_summary":
            self._create_assembly_summary(tree, output_path, compress, include_genomes)
        elif format_type == "accession2taxid":
            self._create_accession2taxid(tree, output_path, compress, include_genomes)
        else:
            raise ExportError(f"Unsupported MetaCache format_type: {format_type}")

        logger.info(f"MetaCache export completed: {output_path}")

    def _create_ncbi_taxonomy(
        self, tree: TaxonomyTree, output_path: Path, compress: bool
    ) -> None:
        """Create NCBI taxonomy format files (names.dmp, nodes.dmp)."""
        logger.info("Creating NCBI taxonomy format files")

        names_path = output_path / "names.dmp"
        nodes_path = output_path / "nodes.dmp"

        self._write_names_file(tree, names_path, compress)
        self._write_nodes_file(tree, nodes_path, compress)

        logger.info(f"Created NCBI taxonomy files: {names_path}, {nodes_path}")

    def _create_assembly_summary(
        self,
        tree: TaxonomyTree,
        output_path: Path,
        compress: bool,
        include_genomes: bool,
    ) -> None:
        """Create assembly_summary.txt format for MetaCache."""
        logger.info("Creating assembly summary format")

        if not include_genomes or tree.genome_count == 0:
            logger.warning(
                "No genome information available for assembly summary format"
            )
            # Create empty file with headers
            summary_path = output_path / "assembly_summary.txt"
            self._write_empty_assembly_summary(summary_path, compress)
            return

        summary_path = output_path / "assembly_summary.txt"
        genomes_mapped = 0

        with open(summary_path, "w", encoding="utf-8", newline="\n") as f:
            # Write required comment lines
            f.write(
                "# assembly_accession\tbioproject\tbiosample\ttaxid\tspecies_taxid\t"
                "organism_name\tasm_name\tftp_path\n"
            )
            f.write("# MetaCache assembly summary generated by FlexTaxD\n")

            for node in tree:
                genomes = tree.get_genomes_for_node(node.tax_id)
                for genome in genomes:
                    # Assembly accession (required by MetaCache)
                    assembly_acc = genome.assembly_accession or genome.genome_id

                    # Get species-level taxid (traverse up to find species)
                    species_taxid = self._find_species_taxid(tree, node)

                    # Create assembly summary line
                    fields = [
                        assembly_acc,  # assembly_accession
                        "",  # bioproject (empty)
                        "",  # biosample (empty)
                        str(node.tax_id),  # taxid
                        str(species_taxid),  # species_taxid
                        node.name,  # organism_name
                        f"{node.name} assembly",  # asm_name
                        "",  # ftp_path (empty)
                    ]

                    f.write("\t".join(fields) + "\n")
                    genomes_mapped += 1

        logger.info(f"Created assembly summary with {genomes_mapped} genome entries")

        if compress:
            from ..utils.subprocess_utils import compress_file

            compress_file(summary_path)

    def _create_accession2taxid(
        self,
        tree: TaxonomyTree,
        output_path: Path,
        compress: bool,
        include_genomes: bool,
    ) -> None:
        """Create accession2taxid mapping file for MetaCache."""
        logger.info("Creating accession2taxid mapping format")

        if not include_genomes or tree.genome_count == 0:
            logger.warning("No genome information available for accession2taxid format")
            # Create empty file with headers
            mapping_path = output_path / "accession2taxid.txt"
            self._write_empty_accession_mapping(mapping_path, compress)
            return

        mapping_path = output_path / "accession2taxid.txt"
        sequences_mapped = 0

        with open(mapping_path, "w", encoding="utf-8", newline="\n") as f:
            # NCBI accession2taxid format header
            f.write("accession\taccession.version\ttaxid\tgi\n")

            for node in tree:
                genomes = tree.get_genomes_for_node(node.tax_id)
                for genome in genomes:
                    # Map primary genome ID
                    accession = genome.genome_id
                    f.write(f"{accession}\t{accession}\t{node.tax_id}\t0\n")
                    sequences_mapped += 1

                    # Map assembly accession if different
                    if (
                        genome.assembly_accession
                        and genome.assembly_accession != genome.genome_id
                    ):
                        acc = genome.assembly_accession
                        f.write(f"{acc}\t{acc}\t{node.tax_id}\t0\n")
                        sequences_mapped += 1

                    # Extract and map additional accessions
                    additional_accs = self._extract_accessions(genome.genome_id)
                    for acc in additional_accs:
                        f.write(f"{acc}\t{acc}\t{node.tax_id}\t0\n")
                        sequences_mapped += 1

        logger.info(
            f"Created accession2taxid mapping with {sequences_mapped} accession entries"
        )

        if compress:
            from ..utils.subprocess_utils import compress_file

            compress_file(mapping_path)

    def _write_names_file(
        self, tree: TaxonomyTree, output_path: Path, compress: bool
    ) -> None:
        """Write NCBI names.dmp format file."""
        with open(output_path, "w", encoding="utf-8", newline="\n") as f:
            for node in tree:
                escaped_name = self._escape_name(node.name)
                # NCBI names.dmp format: tax_id | name | unique name | name class |
                f.write(
                    f"{node.tax_id}\t|\t{escaped_name}\t|\t\t|\tscientific name\t|\n"
                )

        if compress:
            from ..utils.subprocess_utils import compress_file

            compress_file(output_path)

    def _write_nodes_file(
        self, tree: TaxonomyTree, output_path: Path, compress: bool
    ) -> None:
        """Write NCBI nodes.dmp format file."""
        with open(output_path, "w", encoding="utf-8", newline="\n") as f:
            for node in tree:
                # Parent ID validation
                parent_id = self._validate_parent_id(node, tree)

                # Rank validation
                rank = self._validate_rank(node.rank)

                # NCBI nodes.dmp format (simplified for MetaCache)
                fields = [
                    str(node.tax_id),  # tax_id
                    str(parent_id),  # parent_tax_id
                    rank,  # rank
                    "",  # embl_code
                    "0",  # division_id
                    "1",  # inherited_div_flag
                    "1",  # genetic_code_id
                    "1",  # inherited_gc_flag
                    "1",  # mitochondrial_genetic_code_id
                    "1",  # inherited_mgc_flag
                    "0",  # genbank_hidden_flag
                    "0",  # hidden_subtree_root_flag
                    "",  # comments
                ]

                f.write("\t|\t".join(fields) + "\t|\n")

        if compress:
            from ..utils.subprocess_utils import compress_file

            compress_file(output_path)

    def _write_empty_assembly_summary(self, output_path: Path, compress: bool) -> None:
        """Create empty assembly summary file with headers."""
        with open(output_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(
                "# assembly_accession\tbioproject\tbiosample\ttaxid\tspecies_taxid\t"
                "organism_name\tasm_name\tftp_path\n"
            )
            f.write("# No genome information available\n")

        if compress:
            from ..utils.subprocess_utils import compress_file

            compress_file(output_path)

    def _write_empty_accession_mapping(self, output_path: Path, compress: bool) -> None:
        """Create empty accession2taxid file with headers."""
        with open(output_path, "w", encoding="utf-8", newline="\n") as f:
            f.write("accession\taccession.version\ttaxid\tgi\n")

        if compress:
            from ..utils.subprocess_utils import compress_file

            compress_file(output_path)

    def _find_species_taxid(self, tree: TaxonomyTree, node: Any) -> int:
        """Find species-level taxid by traversing up the tree."""
        current = node
        while current:
            if hasattr(current.rank, "value"):
                rank_str = current.rank.value.lower()
            else:
                rank_str = str(current.rank).lower()

            if rank_str == "species":
                return int(current.tax_id)

            # Move up to parent
            if current.parent_id:
                current = tree.get_node(current.parent_id)
            else:
                break

        # If no species found, return original taxid
        return int(node.tax_id)

    def _validate_parent_id(self, node: Any, tree: TaxonomyTree) -> int:
        """Validate and return proper parent ID for node."""
        # Root nodes should have themselves as parent
        if node.parent_id is None:
            return int(node.tax_id)

        # Validate parent exists in tree
        if tree.get_node(node.parent_id) is None:
            logger.warning(
                f"Node {node.tax_id} references non-existent parent {node.parent_id}, using self as parent"
            )
            return int(node.tax_id)

        return int(node.parent_id)

    def _validate_rank(self, rank: Any) -> str:
        """Validate taxonomic rank for NCBI format."""
        if rank is None:
            return "no rank"

        # Convert rank to string and normalize
        rank_str = str(rank).lower()
        if hasattr(rank, "value"):
            rank_str = rank.value.lower()

        # Map common rank variations to NCBI standard ranks
        rank_mapping = {
            "custom": "no rank",
            "root": "no rank",
            "domain": "superkingdom",
            "kingdom": "kingdom",
            "phylum": "phylum",
            "class": "class",
            "order": "order",
            "family": "family",
            "genus": "genus",
            "species": "species",
            "strain": "no rank",
            "subspecies": "subspecies",
            "varietas": "varietas",
            "forma": "forma",
        }

        return rank_mapping.get(rank_str, rank_str)

    def _escape_name(self, name: str) -> str:
        """Escape special characters in taxonomic names for NCBI format."""
        if not name:
            return "unnamed"

        # Replace tabs with spaces (critical for format integrity)
        escaped = name.replace("\t", " ")

        # Replace pipes with semicolons (pipes are field separators)
        escaped = escaped.replace("|", ";")

        # Replace newlines with spaces
        escaped = escaped.replace("\n", " ").replace("\r", " ")

        # Trim whitespace and collapse multiple spaces
        escaped = " ".join(escaped.split())

        # Ensure name is not empty after cleaning
        return escaped if escaped else "unnamed"

    def _extract_accessions(self, genome_id: str) -> List[str]:
        """Extract additional accessions from genome ID."""
        accessions: List[str] = []

        # Handle common separators in genome IDs
        separators = ["|", ";", ",", " "]
        parts = [genome_id]

        for sep in separators:
            new_parts: List[str] = []
            for part in parts:
                new_parts.extend(part.split(sep))
            parts = new_parts

        # Filter for valid accession-like strings
        for part in parts:
            part = part.strip()
            if part and part != genome_id and len(part) > 3:
                # Basic validation for accession format
                if any(c.isalpha() for c in part) and any(c.isdigit() for c in part):
                    accessions.append(part)

        return accessions

    def generate_taxid_fasta_example(
        self, tree: TaxonomyTree, output_path: Path
    ) -> None:
        """Generate example of taxid-annotated FASTA headers for reference.

        This creates a documentation file showing how FASTA headers should
        be formatted for MetaCache with taxid annotations.
        """
        example_path = output_path / "fasta_header_examples.txt"

        with open(example_path, "w", encoding="utf-8") as f:
            f.write("# Example FASTA headers with taxid annotations for MetaCache\n")
            f.write("# Format: >accession | taxid|TAXID_NUMBER\n\n")

            count = 0
            for node in tree:
                genomes = tree.get_genomes_for_node(node.tax_id)
                for genome in genomes:
                    if count >= 10:  # Limit examples
                        break
                    f.write(f">{genome.genome_id} | taxid|{node.tax_id}\n")
                    f.write("ATCGATCGATCG...\n\n")
                    count += 1
                if count >= 10:
                    break

            f.write(
                "# Use these header formats when creating FASTA files for MetaCache\n"
            )

        logger.info(f"Created FASTA header examples: {example_path}")

    def validate_export(
        self, output_path: Path, format_type: str = "ncbi_taxonomy"
    ) -> Dict[str, Any]:
        """Validate the created MetaCache taxonomy files."""
        try:
            validation_results: Dict[str, Any] = {
                "valid": True,
                "files_created": [],
                "errors": [],
                "format": f"MetaCache ({format_type})",
            }

            # Check files based on format type
            if format_type == "ncbi_taxonomy":
                required_files = ["names.dmp", "nodes.dmp"]
            elif format_type == "assembly_summary":
                required_files = ["assembly_summary.txt"]
            elif format_type == "accession2taxid":
                required_files = ["accession2taxid.txt"]
            else:
                validation_results["valid"] = False
                validation_results["errors"].append(
                    f"Unknown format type: {format_type}"
                )
                return validation_results

            for filename in required_files:
                file_path = output_path / filename
                if file_path.exists():
                    validation_results["files_created"].append(filename)
                else:
                    validation_results["valid"] = False
                    validation_results["errors"].append(
                        f"Required file missing: {filename}"
                    )

            # Format-specific validation
            if format_type == "assembly_summary":
                summary_file = output_path / "assembly_summary.txt"
                if summary_file.exists():
                    try:
                        with open(summary_file, "r") as f:
                            lines = f.readlines()
                            if len(lines) < 2 or not lines[0].startswith("#"):
                                validation_results["errors"].append(
                                    "assembly_summary.txt: Invalid format"
                                )
                    except Exception as e:
                        validation_results["errors"].append(
                            f"assembly_summary.txt: Read error - {e}"
                        )

            if validation_results["errors"]:
                validation_results["valid"] = False

            return validation_results

        except Exception as e:
            return {"valid": False, "error": str(e)}
