"""Unit tests for MetaCache exporter."""

import pytest
import tempfile
from pathlib import Path
from unittest.mock import Mock, patch

from flextaxd.core.models import TaxonomyTree, TaxonomyNode, TaxonomicRank, GenomeInfo
from flextaxd.core.exceptions import ExportError
from flextaxd.exporters.metacache import MetaCacheExporter


class TestMetaCacheExporter:
    """Test MetaCache format exporter."""

    def test_exporter_properties(self):
        """Test exporter basic properties."""
        exporter = MetaCacheExporter()
        assert exporter.exporter_name == "metacache"
        assert ".dmp" in exporter.file_extensions
        assert ".txt" in exporter.file_extensions
        assert ".tsv" in exporter.file_extensions
        assert exporter.requires_directory is True

    def test_export_ncbi_taxonomy_format(self):
        """Test export with NCBI taxonomy format (default)."""
        exporter = MetaCacheExporter()
        tree = self._create_test_tree()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.export(tree, output_path, format_type="ncbi_taxonomy")

            # Should create NCBI taxonomy files
            names_file = output_path / "names.dmp"
            nodes_file = output_path / "nodes.dmp"

            assert names_file.exists()
            assert nodes_file.exists()

            # Check content format
            names_content = names_file.read_text()
            nodes_content = nodes_file.read_text()

            assert "1\t|\troot\t|\t\t|\tscientific name\t|\n" in names_content
            assert "1\t|\t1\t|\tno rank\t|" in nodes_content

    def test_export_assembly_summary_format(self):
        """Test export with assembly summary format."""
        exporter = MetaCacheExporter()
        tree = self._create_test_tree_with_genomes()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.export(tree, output_path, format_type="assembly_summary")

            # Should create assembly summary file
            summary_file = output_path / "assembly_summary.txt"
            assert summary_file.exists()

            content = summary_file.read_text()

            # Should have header comments
            assert "# assembly_accession\tbioproject\tbiosample\ttaxid" in content
            assert "# MetaCache assembly summary generated by FlexTaxD" in content

            # Should have genome entries
            assert "GCF_000005825.2\t\t\t562\t562\tEscherichia coli" in content

    def test_export_accession2taxid_format(self):
        """Test export with accession2taxid format."""
        exporter = MetaCacheExporter()
        tree = self._create_test_tree_with_genomes()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.export(tree, output_path, format_type="accession2taxid")

            # Should create accession2taxid file
            mapping_file = output_path / "accession2taxid.txt"
            assert mapping_file.exists()

            content = mapping_file.read_text()

            # Should have proper header
            assert "accession\taccession.version\ttaxid\tgi\n" in content

            # Should have genome mappings
            assert "NC_000913\tNC_000913\t562\t0\n" in content
            assert "GCF_000005825.2\tGCF_000005825.2\t562\t0\n" in content

    def test_export_without_genomes(self):
        """Test export when no genomes are present."""
        exporter = MetaCacheExporter()
        tree = self._create_tree_without_genomes()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)

            # Test assembly summary format without genomes
            exporter.export(tree, output_path, format_type="assembly_summary")

            summary_file = output_path / "assembly_summary.txt"
            assert summary_file.exists()

            content = summary_file.read_text()
            assert "# No genome information available" in content

    def test_export_with_compression(self):
        """Test export with file compression."""
        exporter = MetaCacheExporter()
        tree = self._create_test_tree()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)

            with patch(
                "flextaxd.utils.subprocess_utils.compress_file"
            ) as mock_compress:
                exporter.export(
                    tree, output_path, format_type="ncbi_taxonomy", compress=True
                )

                # Should call compression for files
                assert mock_compress.call_count >= 2  # names.dmp, nodes.dmp

    def test_species_taxid_finding(self):
        """Test finding species-level taxid in assembly summary."""
        exporter = MetaCacheExporter()
        tree = self._create_hierarchical_tree()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.export(tree, output_path, format_type="assembly_summary")

            summary_file = output_path / "assembly_summary.txt"
            content = summary_file.read_text()

            # Should find correct species taxid in hierarchy
            assert "562\t562\t" in content  # species node should reference itself

    def test_name_escaping(self):
        """Test proper escaping of taxonomic names."""
        exporter = MetaCacheExporter()
        tree = self._create_tree_with_special_names()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.export(tree, output_path, format_type="ncbi_taxonomy")

            names_file = output_path / "names.dmp"
            content = names_file.read_text()

            # Should escape special characters
            assert "Special;Name" in content  # Pipe replaced with semicolon
            assert "Tab Name" in content  # Tab replaced with space

    def test_accession_extraction(self):
        """Test extraction of additional accessions."""
        exporter = MetaCacheExporter()
        tree = self._create_tree_with_complex_accessions()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.export(tree, output_path, format_type="accession2taxid")

            mapping_file = output_path / "accession2taxid.txt"
            content = mapping_file.read_text()

            # Should extract multiple accessions from complex genome ID
            lines = content.strip().split("\n")
            accession_lines = [
                line for line in lines if not line.startswith("accession")
            ]

            # Should have multiple mappings
            assert len(accession_lines) >= 2

    def test_invalid_format_type_error(self):
        """Test error handling with invalid format type."""
        exporter = MetaCacheExporter()
        tree = self._create_test_tree()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)

            with pytest.raises(ExportError, match="Unsupported MetaCache format_type"):
                exporter.export(tree, output_path, format_type="invalid_format")

    def test_parent_validation(self):
        """Test parent ID validation in nodes.dmp."""
        exporter = MetaCacheExporter()
        tree = self._create_tree_with_invalid_parents()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.export(tree, output_path, format_type="ncbi_taxonomy")

            nodes_file = output_path / "nodes.dmp"
            content = nodes_file.read_text()

            # Should correct invalid parent references
            assert "999\t|\t999\t|\t" in content  # Self-parent for orphan

    def test_rank_mapping(self):
        """Test taxonomic rank mapping."""
        exporter = MetaCacheExporter()
        tree = self._create_tree_with_various_ranks()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.export(tree, output_path, format_type="ncbi_taxonomy")

            nodes_file = output_path / "nodes.dmp"
            content = nodes_file.read_text()

            # Should map ranks correctly
            assert "superkingdom" in content  # Domain -> superkingdom
            assert "no rank" in content  # Custom -> no rank

    def test_fasta_header_examples_generation(self):
        """Test generation of FASTA header examples."""
        exporter = MetaCacheExporter()
        tree = self._create_test_tree_with_genomes()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.generate_taxid_fasta_example(tree, output_path)

            example_file = output_path / "fasta_header_examples.txt"
            assert example_file.exists()

            content = example_file.read_text()

            # Should have example headers with taxid annotations
            assert ">NC_000913 | taxid|562" in content
            assert "ATCGATCGATCG..." in content
            assert (
                "# Use these header formats when creating FASTA files for MetaCache"
                in content
            )

    def test_validation_method(self):
        """Test export validation method."""
        exporter = MetaCacheExporter()
        tree = self._create_test_tree()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.export(tree, output_path, format_type="ncbi_taxonomy")

            # Validate export
            results = exporter.validate_export(output_path, "ncbi_taxonomy")

            assert results["valid"] is True
            assert "names.dmp" in results["files_created"]
            assert "nodes.dmp" in results["files_created"]
            assert results["format"] == "MetaCache (ncbi_taxonomy)"

    def test_validation_assembly_summary(self):
        """Test validation of assembly summary format."""
        exporter = MetaCacheExporter()
        tree = self._create_test_tree_with_genomes()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)
            exporter.export(tree, output_path, format_type="assembly_summary")

            results = exporter.validate_export(output_path, "assembly_summary")

            assert results["valid"] is True
            assert "assembly_summary.txt" in results["files_created"]

    def test_empty_tree_error(self):
        """Test error handling with empty tree."""
        exporter = MetaCacheExporter()
        empty_tree = TaxonomyTree()

        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir)

            with pytest.raises(ExportError, match="Cannot export empty taxonomy tree"):
                exporter.export(empty_tree, output_path)

    def _create_test_tree(self):
        """Create basic test taxonomy tree."""
        tree = TaxonomyTree()

        root = TaxonomyNode(tax_id=1, name="root", rank=TaxonomicRank.CUSTOM)
        tree.add_node(root)

        bacteria = TaxonomyNode(
            tax_id=2, name="Bacteria", rank=TaxonomicRank.SUPERKINGDOM, parent_id=1
        )
        tree.add_node(bacteria)

        return tree

    def _create_test_tree_with_genomes(self):
        """Create test tree with genomes."""
        tree = TaxonomyTree()

        root = TaxonomyNode(tax_id=1, name="root", rank=TaxonomicRank.CUSTOM)
        tree.add_node(root)

        ecoli = TaxonomyNode(
            tax_id=562, name="Escherichia coli", rank=TaxonomicRank.SPECIES, parent_id=1
        )
        tree.add_node(ecoli)

        # Add genome with assembly accession
        genome = GenomeInfo(
            genome_id="NC_000913",
            tax_id=562,
            sequence_type="genome",
            assembly_accession="GCF_000005825.2",
        )
        tree.add_genome(genome)

        return tree

    def _create_tree_without_genomes(self):
        """Create tree without genomes."""
        tree = TaxonomyTree()

        root = TaxonomyNode(tax_id=1, name="root", rank=TaxonomicRank.CUSTOM)
        tree.add_node(root)

        bacteria = TaxonomyNode(
            tax_id=2, name="Bacteria", rank=TaxonomicRank.SUPERKINGDOM, parent_id=1
        )
        tree.add_node(bacteria)

        return tree

    def _create_hierarchical_tree(self):
        """Create hierarchical tree for species finding test."""
        tree = TaxonomyTree()

        root = TaxonomyNode(tax_id=1, name="root", rank=TaxonomicRank.CUSTOM)
        tree.add_node(root)

        bacteria = TaxonomyNode(
            tax_id=2, name="Bacteria", rank=TaxonomicRank.SUPERKINGDOM, parent_id=1
        )
        tree.add_node(bacteria)

        genus = TaxonomyNode(
            tax_id=561, name="Escherichia", rank=TaxonomicRank.GENUS, parent_id=2
        )
        tree.add_node(genus)

        species = TaxonomyNode(
            tax_id=562,
            name="Escherichia coli",
            rank=TaxonomicRank.SPECIES,
            parent_id=561,
        )
        tree.add_node(species)

        # Add genome to species
        genome = GenomeInfo(genome_id="NC_000913", tax_id=562, sequence_type="genome")
        tree.add_genome(genome)

        return tree

    def _create_tree_with_special_names(self):
        """Create tree with special characters in names."""
        tree = TaxonomyTree()

        root = TaxonomyNode(tax_id=1, name="root", rank=TaxonomicRank.CUSTOM)
        tree.add_node(root)

        special = TaxonomyNode(
            tax_id=100,
            name="Special|Name\tWith\nChars",
            rank=TaxonomicRank.GENUS,
            parent_id=1,
        )
        tree.add_node(special)

        return tree

    def _create_tree_with_complex_accessions(self):
        """Create tree with complex genome accessions."""
        tree = TaxonomyTree()

        root = TaxonomyNode(tax_id=1, name="root", rank=TaxonomicRank.CUSTOM)
        tree.add_node(root)

        ecoli = TaxonomyNode(
            tax_id=562, name="Escherichia coli", rank=TaxonomicRank.SPECIES, parent_id=1
        )
        tree.add_node(ecoli)

        # Complex genome ID with multiple accessions
        genome = GenomeInfo(
            genome_id="NC_000913|GCF_000005825.2|gi:48994873",
            tax_id=562,
            sequence_type="genome",
        )
        tree.add_genome(genome)

        return tree

    def _create_tree_with_invalid_parents(self):
        """Create tree with invalid parent references."""
        tree = TaxonomyTree()

        root = TaxonomyNode(tax_id=1, name="root", rank=TaxonomicRank.CUSTOM)
        tree.add_node(root)

        orphan = TaxonomyNode(
            tax_id=999, name="Orphan", rank=TaxonomicRank.GENUS, parent_id=888
        )
        tree.add_node(orphan)

        return tree

    def _create_tree_with_various_ranks(self):
        """Create tree with various taxonomic ranks."""
        tree = TaxonomyTree()

        root = TaxonomyNode(tax_id=1, name="root", rank=TaxonomicRank.CUSTOM)
        tree.add_node(root)

        domain = TaxonomyNode(
            tax_id=2, name="Bacteria", rank=TaxonomicRank.DOMAIN, parent_id=1
        )
        tree.add_node(domain)

        return tree
